Rozdział 13. Wprowadzenie do obiektów Pandas

In [1]:
import pandas as pd
pd.__version__

'3.0.2'

In [2]:
pd?

Type:        module
String form: <module 'pandas' from '/Users/aandrzejewskaromanowska/miniconda3/envs/data_science/lib/python3.13/site-packages/pandas/__init__.py'>
File:        ~/miniconda3/envs/data_science/lib/python3.13/site-packages/pandas/__init__.py
Docstring:
pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

In [2]:
import numpy as np
import pandas as pd

Obiekt typu Series - ma values i index

In [ ]:
# pd.Series(dane, index=indeks)

data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
data[1]

np.float64(0.5)

In [8]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['b']

np.float64(0.5)

In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [7]:
population_dict = {'California': 353725, 'Texas': 744132, 'Florida': 752372, 'New York': 7372, 'Pennsylvania': 82637264}
population = pd.Series(population_dict)
population

California        353725
Texas             744132
Florida           752372
New York            7372
Pennsylvania    82637264
dtype: int64

In [13]:
population['California']

np.int64(353725)

In [14]:
population['California':'Florida']

California    353725
Texas         744132
Florida       752372
dtype: int64

In [15]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [17]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [18]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: str

Obiekt typu DataFrame
- zbiór obiektów typu Series

In [5]:
# dict od dictionary

area_dict = {'California': 5826326, 'Texas': 8631481, 'Florida': 6381264, 'New York': 7623723, 'Pennsylvania': 82632638}
area = pd.Series(area_dict)
area

California       5826326
Texas            8631481
Florida          6381264
New York         7623723
Pennsylvania    82632638
dtype: int64

In [8]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

              population      area
California        353725   5826326
Texas             744132   8631481
Florida           752372   6381264
New York            7372   7623723
Pennsylvania    82637264  82632638

In [5]:
states.index

Index(['California', 'Texas', 'Florida', 'New York', 'Pennsylvania'], dtype='str')

In [6]:
states.columns

Index(['population', 'area'], dtype='str')

In [7]:
states['area']

California       5826326
Texas            8631481
Florida          6381264
New York         7623723
Pennsylvania    82632638
Name: area, dtype: int64

In [10]:
pd.DataFrame(population, columns=['population'])

              population
California        353725
Texas             744132
Florida           752372
New York            7372
Pennsylvania    82637264

In [15]:
pd.DataFrame({'population': population,
              'area': area})

              population      area
California        353725   5826326
Texas             744132   8631481
Florida           752372   6381264
New York            7372   7623723
Pennsylvania    82637264  82632638

In [16]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

        foo       bar
a  0.584055  0.629262
b  0.685745  0.076203
c  0.184587  0.410933

In [17]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [18]:
pd.DataFrame(A)

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

Obiekt typu Index

In [19]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [20]:
ind[1]

np.int64(3)

In [21]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [22]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

In [ ]:
# nie mozna zmienic ich zawartosci
ind[1] = 0

TypeError: Index does not support mutable operations

In [24]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [25]:
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

In [26]:
indA.union(indB)

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [27]:
indA.symmetric_difference(indB)

Index([1, 2, 9, 11], dtype='int64')

Rozdział 14. Indeksowanie i wybieranie

In [28]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [29]:
data['b']

np.float64(0.5)

In [30]:
'a' in data

True

In [31]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='str')

In [32]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [33]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [34]:
# slicing z uzyciem jawnego indeksu
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [35]:
# slicing z uzyciem niejawnego indeksu liczbowego
data[0:2]

a    0.25
b    0.50
dtype: float64

In [ ]:
# maskowanie - filtrowanie danych za pomoca warunkow logicznych (tworzy 'maske' - tablice z True i False)
# nałoenie maski (filtru)
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [ ]:
# fancy indexing (zaawansowane indeksowanie - zamiast filtrowac indeksami od-do, podajemy konkretne indeksy w swojej kolejnosci)
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

Indeksatory: loc i iloc

In [3]:
# to atrybuty aby bylo wiadomo czy uzywamy jawnego czy niejawnego indeksu
# loc - pozwala indeksowac i wycinać fragmenty obiektu na podstawie JAWNEGO indeksu

data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: str

In [ ]:
# uzyty niejawny indeks
data[1:3]

3    b
5    c
dtype: str

In [40]:
data.loc[1]

'a'

In [ ]:
# uzyty jawny indeks
data.loc[1:3]

1    a
3    b
dtype: str

In [4]:
# uzyty niejawny indeks
data.iloc[1:3]

3    b
5    c
dtype: str

Wybór danych z obiektów DataFrame

In [9]:
states

              population      area
California        353725   5826326
Texas             744132   8631481
Florida           752372   6381264
New York            7372   7623723
Pennsylvania    82637264  82632638

In [10]:
states['area']

California       5826326
Texas            8631481
Florida          6381264
New York         7623723
Pennsylvania    82632638
Name: area, dtype: int64

In [11]:
states.area

California       5826326
Texas            8631481
Florida          6381264
New York         7623723
Pennsylvania    82632638
Name: area, dtype: int64

In [12]:
states['density'] = states['population'] / states['area']

In [13]:
states

              population      area   density
California        353725   5826326  0.060712
Texas             744132   8631481  0.086211
Florida           752372   6381264  0.117903
New York            7372   7623723  0.000967
Pennsylvania    82637264  82632638  1.000056

In [14]:
states.values

array([[3.53725000e+05, 5.82632600e+06, 6.07115016e-02],
       [7.44132000e+05, 8.63148100e+06, 8.62113929e-02],
       [7.52372000e+05, 6.38126400e+06, 1.17903287e-01],
       [7.37200000e+03, 7.62372300e+06, 9.66981618e-04],
       [8.26372640e+07, 8.26326380e+07, 1.00005598e+00]])

In [15]:
states.T

,California,Texas,Florida,New York,Pennsylvania
population,3.537250e+05,7.441320e+05,7.523720e+05,7.372000e+03,8.263726e+07
area,5.826326e+06,8.631481e+06,6.381264e+06,7.623723e+06,8.263264e+07
density,6.071150e-02,8.621139e-02,1.179033e-01,9.669816e-04,1.000056e+00

In [16]:
states.values[0]

array([3.53725000e+05, 5.82632600e+06, 6.07115016e-02])

In [17]:
states['area']

California       5826326
Texas            8631481
Florida          6381264
New York         7623723
Pennsylvania    82632638
Name: area, dtype: int64

In [18]:
states.iloc[:3, :2]

            population     area
California      353725  5826326
Texas           744132  8631481
Florida         752372  6381264

In [19]:
states.loc[:'Florida', :'population']

            population
California      353725
Texas           744132
Florida         752372

In [21]:
states.loc[states.density > 1, ['population', 'density']]

              population   density
Pennsylvania    82637264  1.000056

In [22]:
states.iloc[0, 2] = 90
states

              population      area    density
California        353725   5826326  90.000000
Texas             744132   8631481   0.086211
Florida           752372   6381264   0.117903
New York            7372   7623723   0.000967
Pennsylvania    82637264  82632638   1.000056

In [23]:
states['Florida':'New York']

          population     area   density
Florida       752372  6381264  0.117903
New York        7372  7623723  0.000967

In [24]:
states[1:3]

         population     area   density
Texas        744132  8631481  0.086211
Florida      752372  6381264  0.117903

In [25]:
states[states.density > 1]

              population      area    density
California        353725   5826326  90.000000
Pennsylvania    82637264  82632638   1.000056

Rozdział 15. Operacje na danych w Pandas

In [26]:
rng = np.random.default_rng(42)
ser = pd.Series(rng.integers(0, 10, 4))
ser

0    0
1    7
2    6
3    4
dtype: int64

In [27]:
df = pd.DataFrame(rng.integers(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  4  8  0  6
1  2  0  5  9
2  7  7  7  7

In [28]:
np.exp(ser)

0       1.000000
1    1096.633158
2     403.428793
3      54.598150
dtype: float64

In [29]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [30]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [31]:
A = pd.DataFrame(rng.integers(0, 20, (2, 2)),
                 columns=['a', 'b'])
A

    a  b
0  10  2
1  16  9

In [32]:
B = pd.DataFrame(rng.integers(1, 10, (3, 3)),
                 columns=['b', 'a', 'c'])
B

   b  a  c
0  5  4  2
1  9  8  6
2  4  8  5

In [33]:
A + B

      a     b   c
0  14.0   7.0 NaN
1  24.0  18.0 NaN
2   NaN   NaN NaN

In [34]:
A.add(B, fill_value=A.values.mean())

       a      b      c
0  14.00   7.00  11.25
1  24.00  18.00  15.25
2  17.25  13.25  14.25

In [35]:
A = rng.integers(10, size=(3, 4))
A

array([[4, 4, 2, 0],
       [5, 8, 0, 8],
       [8, 2, 6, 1]])

In [36]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 1,  4, -2,  8],
       [ 4, -2,  4,  1]])

In [37]:
df = pd.DataFrame(A, columns=['Q', 'R', 'S', 'T'])
df - df.iloc[0]

   Q  R  S  T
0  0  0  0  0
1  1  4 -2  8
2  4 -2  4  1

In [38]:
df.subtract(df['R'], axis=0)

   Q  R  S  T
0  0  0 -2 -4
1 -3  0 -8  0
2  6  0  4 -1

In [39]:
halfrow = df.iloc[0, ::2]
halfrow

Q    4
S    2
Name: 0, dtype: int64

In [41]:
df - halfrow

     Q   R    S   T
0  0.0 NaN  0.0 NaN
1  1.0 NaN -2.0 NaN
2  4.0 NaN  4.0 NaN

Rozdział 16. Obsługa brakujących danych

In [ ]:
# None jako rodzaj wartownika
# (None jest obiektem, dtype=object) - dłusze obliczenia bo na poziomie obiektu Pythona, a nie liczb Numpy/Pandas
# Nie obsługuje z nim operacji arytmetycznych

vals1 = np.array([1, None, 2, 3])
vals1

array([1, None, 2, 3], dtype=object)

In [44]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [ ]:
# NaN - No a Number - brakujące dane liczbowe - Z PAKIETU NUMPY (np.nan)
# wartość zmiennoprzecinkowa, szybkie obliczenia, ALE UWAGA - NAN TO WIRUS - wszystko czego dotknie zmienia się w nan

vals2 = np.array([1, np.nan, 3, 4])
vals2

array([ 1., nan,  3.,  4.])

In [46]:
1 + np.nan

nan

In [47]:
vals2.sum()

np.float64(nan)

In [48]:
np.nansum(vals2)

np.float64(8.0)

In [49]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [50]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [52]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [ ]:
# w Pandas łańcuch znaków ma dtype=object

In [54]:
# format z brakiem danych - z duzej litery
pd.Series([1, np.nan, 2, None, 3, pd.NA], dtype='Int32')

0       1
1    <NA>
2       2
3    <NA>
4       3
5    <NA>
dtype: Int32

In [ ]:
# isnull, notnull, dropna, fillna

In [55]:
data = pd.Series([1, np.nan, 'hello', None])

In [56]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [58]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [59]:
data.dropna()

0        1
2    hello
dtype: object

In [60]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [61]:
df.dropna()

     0    1  2
1  2.0  3.0  5

In [62]:
df.dropna(axis='columns')

   2
0  2
1  5
2  6

In [63]:
df[3] = np.nan
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [64]:
df.dropna(axis='columns', how='all')

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df.dropna(axis='rows', thresh=3) # ile wartosci musi byc ok aby były zachowane wiersze

     0    1  2   3
1  2.0  3.0  5 NaN

Rozdział 17. Indeksowanie hierarchiczne

In [ ]:
# indeksowanie wielokrotne inaczej - multiindexing
# typ MultiIndex

In [8]:
# Zły sposób na wielokrotne indeksowanie series - KROTKI
index = [('California', 2010), ('California', 2020),
         ('New York', 2010), ('New York', 2020),
         ('Texas', 2010), ('Texas', 2020)]
population = [324242, 2323232, 242424, 23232432, 224242, 242424]
pop = pd.Series(population, index=index)
pop

(California, 2010)      324242
(California, 2020)     2323232
(New York, 2010)        242424
(New York, 2020)      23232432
(Texas, 2010)           224242
(Texas, 2020)           242424
dtype: int64

In [67]:
pop[('California', 2020):('Texas', 2010)]

(California, 2020)     2323232
(New York, 2010)        242424
(New York, 2020)      23232432
(Texas, 2010)           224242
dtype: int64

In [69]:
# ale juz wybranie wszystkiego z 2010 jest mozolne
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    324242
(New York, 2010)      242424
(Texas, 2010)         224242
dtype: int64

In [9]:
# Lepszy sposób - MultiIndex z Pandas
index = pd.MultiIndex.from_tuples(index)

In [10]:
pop = pop.reindex(index)
pop

California  2010      324242
            2020     2323232
New York    2010      242424
            2020    23232432
Texas       2010      224242
            2020      242424
dtype: int64

In [72]:
# mozna zastosowac slicing tutaj
pop[:, 2020]

California     2323232
New York      23232432
Texas           242424
dtype: int64

In [73]:
pop_df = pop.unstack()
pop_df

              2010      2020
California  324242   2323232
New York    242424  23232432
Texas       224242    242424

In [74]:
pop_df.stack()

California  2010      324242
            2020     2323232
New York    2010      242424
            2020    23232432
Texas       2010      224242
            2020      242424
dtype: int64

In [75]:
# dodanie wymiaru
pop_df = pd.DataFrame({'total': pop,
                       'under18': [5756, 5336, 87797, 2372, 2323, 4342]})
pop_df

                    total  under18
California 2010    324242     5756
           2020   2323232     5336
New York   2010    242424    87797
           2020  23232432     2372
Texas      2010    224242     2323
           2020    242424     4342

In [76]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

                2010      2020
California  0.017752  0.002297
New York    0.362163  0.000102
Texas       0.010359  0.017911

In [2]:
import numpy as np
import pandas as pd

In [ ]:
# Tworzenie multiindex sposób 1
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

        data1     data2
a 1  0.116355  0.625440
  2  0.584310  0.430148
b 1  0.864877  0.554282
  2  0.439593  0.003742

In [4]:
# Tworzenie multiindex sposób 2 - uzycie jawnego konstruktora
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [5]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [6]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [7]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
              codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [11]:
pop.index.names = ['state', 'year']
pop

state       year
California  2010      324242
            2020     2323232
New York    2010      242424
            2020    23232432
Texas       2010      224242
            2020      242424
dtype: int64

In [ ]:
# Dane medyczne - index i columns mają multiindex
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])
# Generowanie przykładowych danych, 4 wiersze na 6 kolumn, zaokraglone do 1 miejsca po przecinku
data = np.round(np.random.rand(4, 6), 1)
# slicing, wybierza wszystkie wiersze (:), i co drugą kolumne (start:stop:krok(2)) -> mnozy razy 10
data[:, ::2] *= 10
# broadcasting - do wszystkich elementow dodaje 37
data += 37

# Tworzę ramkę danych
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      46.0  37.3  47.0  37.4  40.0  37.4
     2      44.0  37.0  37.0  37.9  40.0  37.1
2014 1      38.0  37.7  43.0  37.8  42.0  37.2
     2      47.0  37.2  44.0  37.7  37.0  37.9

In [13]:
health_data['Guido']

type          HR  Temp
year visit
2013 1      47.0  37.4
     2      37.0  37.9
2014 1      43.0  37.8
     2      44.0  37.7

In [14]:
pop

state       year
California  2010      324242
            2020     2323232
New York    2010      242424
            2020    23232432
Texas       2010      224242
            2020      242424
dtype: int64

In [15]:
pop['California', 2010]

np.int64(324242)

In [16]:
pop['California']

year
2010     324242
2020    2323232
dtype: int64

In [ ]:
# slicing
pop['California':'New York']

state       year
California  2010      324242
            2020     2323232
New York    2010      242424
            2020    23232432
dtype: int64

In [19]:
pop[:, 2010]

state
California    324242
New York      242424
Texas         224242
dtype: int64

In [ ]:
# maskowanie
pop[pop < 250000]

state     year
New York  2010    242424
Texas     2010    224242
          2020    242424
dtype: int64

In [22]:
# fancy indexing
pop[['California', 'Texas']]

state       year
California  2010     324242
            2020    2323232
Texas       2010     224242
            2020     242424
dtype: int64

In [23]:
health_data['Guido', 'HR']

year  visit
2013  1        47.0
      2        37.0
2014  1        43.0
      2        44.0
Name: (Guido, HR), dtype: float64

In [24]:
health_data.iloc[:2, :2]

subject      Bob
type          HR  Temp
year visit
2013 1      46.0  37.3
     2      44.0  37.0

In [25]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        46.0
      2        44.0
2014  1        38.0
      2        47.0
Name: (Bob, HR), dtype: float64

In [27]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit
2013 1      46.0  47.0  40.0
2014 1      38.0  43.0  42.0

MultiIndex - zmiana kolejności

In [33]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.236874
      2      0.429358
c     1      0.947001
      2      0.634894
b     1      0.375866
      2      0.235643
dtype: float64

In [34]:
try:
    data['a':'b']
except KeyError as e:
    print("KeyError", e)

KeyError 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [35]:
data['a':'b']

UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [36]:
data = data.sort_index()
data

char  int
a     1      0.236874
      2      0.429358
b     1      0.375866
      2      0.235643
c     1      0.947001
      2      0.634894
dtype: float64

In [39]:
data['a':'b']

char  int
a     1      0.236874
      2      0.429358
b     1      0.375866
      2      0.235643
dtype: float64

In [40]:
pop

state       year
California  2010      324242
            2020     2323232
New York    2010      242424
            2020    23232432
Texas       2010      224242
            2020      242424
dtype: int64

In [41]:
pop.unstack(level=0)

state  California  New York   Texas
year
2010       324242    242424  224242
2020      2323232  23232432  242424

In [42]:
pop.unstack(level=1)

year          2010      2020
state
California  324242   2323232
New York    242424  23232432
Texas       224242    242424

In [43]:
pop.unstack().stack()

state       year
California  2010      324242
            2020     2323232
New York    2010      242424
            2020    23232432
Texas       2010      224242
            2020      242424
dtype: int64

In [44]:
pop_flat = pop.reset_index(name='population')
pop_flat

        state  year  population
0  California  2010      324242
1  California  2020     2323232
2    New York  2010      242424
3    New York  2020    23232432
4       Texas  2010      224242
5       Texas  2020      242424

In [45]:
pop_flat.set_index(['state', 'year'])

                 population
state      year
California 2010      324242
           2020     2323232
New York   2010      242424
           2020    23232432
Texas      2010      224242
           2020      242424

Rozdział 18. Łączenie zbiorów danych - concat i append

In [46]:
# Funkcja tworząca ramkę danych
def make_df(cols, ind):
    """Funkcja, która szybko tworzy ramkę danych"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

In [47]:
# Przykładowa ramka
make_df('ABC', range(3))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [48]:
# Klasa, która pozwoli wyświetlać obok siebie kilka ramek danych
class display(object):
    """Funkcja, wyswietlająca reprezentację HTML wielu obiektów."""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}{1}
    """
    def __init__(self, *args):
        self.args = args
    
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [49]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [54]:
pd.concat?

Signature:
pd.concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool | lib.NoDefault' = <no_default>,
    copy: 'bool | lib.NoDefault' = <no_default>,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : an iterable or mapping of Series or DataFrame objects
    If a mapping is passed, the keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'columns'}, default 0
    The axis to concatenate along.
join : {'inner', 'outer'}, default 'outer'
    How to handle indexes on other axis (or axes).
ignore_index : bool, default False
    If True, do not use the index values along the concatenation axis. The
    resulting axis will be labeled 0, ..., n - 1. This is useful if you are
    concatenating objects where the concatenation axis does not have
    meaningful indexing information. Note the index values on the other
    axes are still respected in the join.
keys : sequence, default None
    If multiple levels passed, should contain tuples. Construct
    hierarchical index using the passed keys as the outermost level.
levels : list of sequences, default None
    Specific levels (unique values) to use for constructing a
    MultiIndex. Otherwise they will be inferred from the keys.
names : list, default None
    Names for the levels in the resulting hierarchical index.
verify_integrity : bool, default False
    Check whether the new concatenated axis contains duplicates. This can
    be very expensive relative to the actual data concatenation.
sort : bool, default False
    Sort non-concatenation axis. One exception to this is when the
    non-concatenation axis is a DatetimeIndex and join='outer' and the axis is
    not already aligned. In that case, the non-concatenation axis is always
    sorted lexicographically.
copy : bool, default False
    This keyword is now ignored; changing its value will have no
    impact on the method.

    .. deprecated:: 3.0.0

        This keyword is ignored and will be removed in pandas 4.0. Since
        pandas 3.0, this method always returns a new object using a lazy
        copy mechanism that defers copies until necessary
        (Copy-on-Write). See the `user guide on Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        for more details.

Returns
-------
object, type of objs
    When concatenating all ``Series`` along the index (axis=0), a
    ``Series`` is returned. When ``objs`` contains at least one
    ``DataFrame``, a ``DataFrame`` is returned. When concatenating along
    the columns (axis=1), a ``DataFrame`` is returned.

See Also
--------
DataFrame.join : Join DataFrames using indexes.
DataFrame.merge : Merge DataFrames by indexes or columns.

Notes
-----
The keys, levels, and names arguments are all optional.

A walkthrough of how this method fits in with other tools for combining
pandas objects can be found `here
<https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html>`__.

It is not recommended to build DataFrames by adding single rows in a
for loop. Build a list of rows and make a DataFrame in a single concat.

Examples
--------
Combine two ``Series``.

>>> s1 = pd.Series(["a", "b"])
>>> s2 = pd.Series(["c", "d"])
>>> pd.concat([s1, s2])
0    a
1    b
0    c
1    d
dtype: str

Clear the existing index and reset it in the result
by setting the ``ignore_index`` option to ``True``.

>>> pd.concat([s1, s2], ignore_index=True)
0    a
1    b
2    c
3    d
dtype: str

Add a hierarchical index at the outermost level of
the data with the ``keys`` option.

>>> pd.concat([s1, s2], keys=["s1", "s2"])
s1  0    a
    1    b
s2  0    c
    1    d
dtype: str

Label the index keys you create with the ``names`` option.

>>> pd.concat([s1, s2], keys=["s1", "s2"], names=["Series name", "Row ID"])
Series name  Row ID
s1           0         a
             1         b
s2           0         c
             1         d
dtype: str

Combine two ``DataFrame`` objects with identical columns.

>>> df1 = pd.DataFrame([["a", 1], ["b", 2]], columns=["letter", "number"])
>>> df1
  letter  number
0      a       1
1      b       2
>>> df2 = pd.DataFrame([["c", 3], ["d", 4]], columns=["letter", "number"])
>>> df2
  letter  number
0      c       3
1      d       4
>>> pd.concat([df1, df2])
  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

Combine ``DataFrame`` objects with overlapping columns
and return everything. Columns outside the intersection will
be filled with ``NaN`` values.

>>> df3 = pd.DataFrame(
...     [["c", 3, "cat"], ["d", 4, "dog"]], columns=["letter", "number", "animal"]
... )
>>> df3
  letter  number animal
0      c       3    cat
1      d       4    dog
>>> pd.concat([df1, df3], sort=False)
  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

Combine ``DataFrame`` objects with overlapping columns
and return only those that are shared by passing ``inner`` to
the ``join`` keyword argument.

>>> pd.concat([df1, df3], join="inner")
  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

Combine ``DataFrame`` objects horizontally along the x axis by
passing in ``axis=1``.

>>> df4 = pd.DataFrame(
...     [["bird", "polly"], ["monkey", "george"]], columns=["animal", "name"]
... )
>>> pd.concat([df1, df4], axis=1)
  letter  number  animal    name
0      a       1    bird   polly
1      b       2  monkey  george

Prevent the result from including duplicate index values with the
``verify_integrity`` option.

>>> df5 = pd.DataFrame([1], index=["a"])
>>> df5
   0
a  1
>>> df6 = pd.DataFrame([2], index=["a"])
>>> df6
   0
a  2
>>> pd.concat([df5, df6], verify_integrity=True)
Traceback (most recent call last):
    ...
ValueError: Indexes have overlapping values: ['a']

Append a single row to the end of a ``DataFrame`` object.

>>> df7 = pd.DataFrame({"a": 1, "b": 2}, index=[0])
>>> df7
    a   b
0   1   2
>>> new_row = pd.Series({"a": 3, "b": 4})
>>> new_row
a    3
b    4
dtype: int64
>>> pd.concat([df7, new_row.to_frame().T], ignore_index=True)
    a   b
0   1   2
1   3   4
File:      ~/miniconda3/envs/data_science/lib/python3.13/site-packages/pandas/core/reshape/concat.py
Type:      function

In [55]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'F', 'E'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    F
6    E
dtype: str

In [56]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
pd.concat([df1, df2])

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [60]:
display('df1', 'df2', 'pd.concat([df1, df2])')

df1
    A   B
1  A1  B1
2  A2  B2

df2
    A   B
3  A3  B3
4  A4  B4

pd.concat([df1, df2])
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [62]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
display('df3', 'df4', "pd.concat([df3, df4], axis='columns')")

df3
    A   B
0  A0  B0
1  A1  B1

df4
    C   D
0  C0  D0
1  C1  D1

pd.concat([df3, df4], axis='columns')
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [63]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index # dopasowanie indeksów
display('x', 'y', 'pd.concat([x, y])')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y])
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [64]:
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print("ValueError", e)

ValueError Indexes have overlapping values: Index([0, 1], dtype='int64')

In [65]:
display('x', 'y', 'pd.concat([x, y], ignore_index=True)')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], ignore_index=True)
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [66]:
display('x', 'y', "pd.concat([x, y], keys=['x', 'y'])")

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], keys=['x', 'y'])
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [ ]:
# łaczenie kolumn, gdzie tylko kilka jest wspólnych
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
display('df5', 'df6', 'pd.concat([df5, df6])') # domyślnie argument join='outer'

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6])
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [68]:
# join='inner'
display('df5', 'df6', "pd.concat([df5, df6], join='inner')")

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join='inner')
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [69]:
# reindex przed złączeniem
pd.concat([df5, df6.reindex(df5.columns, axis=1)])

     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

In [ ]:
# metoda append