Rozdział 13. Wprowadzenie do obiektów Pandas

In [1]:
import pandas as pd
pd.__version__

'3.0.2'

In [2]:
pd?

Type:        module
String form: <module 'pandas' from '/Users/aandrzejewskaromanowska/miniconda3/envs/data_science/lib/python3.13/site-packages/pandas/__init__.py'>
File:        ~/miniconda3/envs/data_science/lib/python3.13/site-packages/pandas/__init__.py
Docstring:
pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

In [11]:
import numpy as np
import pandas as pd

Obiekt typu Series - ma values i index

In [ ]:
# pd.Series(dane, index=indeks)

data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
data[1]

np.float64(0.5)

In [8]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['b']

np.float64(0.5)

In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [12]:
population_dict = {'California': 353725, 'Texas': 744132, 'Florida': 752372, 'New York': 7372, 'Pennsylvania': 82637264}
population = pd.Series(population_dict)
population

California        353725
Texas             744132
Florida           752372
New York            7372
Pennsylvania    82637264
dtype: int64

In [13]:
population['California']

np.int64(353725)

In [14]:
population['California':'Florida']

California    353725
Texas         744132
Florida       752372
dtype: int64

In [15]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [17]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [18]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: str

Obiekt typu DataFrame
- zbiór obiektów typu Series

In [ ]:
# dict od dictionary

area_dict = {'California': 5826326, 'Texas': 8631481, 'Florida': 6381264, 'New York': 7623723, 'Pennsylvania': 82632638}
area = pd.Series(area_dict)
area

California       5826326
Texas            8631481
Florida          6381264
New York         7623723
Pennsylvania    82632638
dtype: int64

In [14]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

              population      area
California        353725   5826326
Texas             744132   8631481
Florida           752372   6381264
New York            7372   7623723
Pennsylvania    82637264  82632638

In [5]:
states.index

Index(['California', 'Texas', 'Florida', 'New York', 'Pennsylvania'], dtype='str')

In [6]:
states.columns

Index(['population', 'area'], dtype='str')

In [7]:
states['area']

California       5826326
Texas            8631481
Florida          6381264
New York         7623723
Pennsylvania    82632638
Name: area, dtype: int64

In [10]:
pd.DataFrame(population, columns=['population'])

              population
California        353725
Texas             744132
Florida           752372
New York            7372
Pennsylvania    82637264

In [15]:
pd.DataFrame({'population': population,
              'area': area})

              population      area
California        353725   5826326
Texas             744132   8631481
Florida           752372   6381264
New York            7372   7623723
Pennsylvania    82637264  82632638

In [16]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

        foo       bar
a  0.584055  0.629262
b  0.685745  0.076203
c  0.184587  0.410933

In [17]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [18]:
pd.DataFrame(A)

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

Obiekt typu Index

In [19]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [20]:
ind[1]

np.int64(3)

In [21]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [22]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

In [ ]:
# nie mozna zmienic ich zawartosci
ind[1] = 0

TypeError: Index does not support mutable operations

In [24]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [25]:
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

In [26]:
indA.union(indB)

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [27]:
indA.symmetric_difference(indB)

Index([1, 2, 9, 11], dtype='int64')

Rozdział 14. Indeksowanie i wybieranie

In [28]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [29]:
data['b']

np.float64(0.5)

In [30]:
'a' in data

True

In [31]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='str')

In [32]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [33]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [34]:
# slicing z uzyciem jawnego indeksu
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [35]:
# slicing z uzyciem niejawnego indeksu liczbowego
data[0:2]

a    0.25
b    0.50
dtype: float64

In [ ]:
# maskowanie - filtrowanie danych za pomoca warunkow logicznych (tworzy 'maske' - tablice z True i False)
# nałoenie maski (filtru)
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [ ]:
# fancy indexing (zaawansowane indeksowanie - zamiast filtrowac indeksami od-do, podajemy konkretne indeksy w swojej kolejnosci)
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

Indeksatory: loc i iloc

In [39]:
# to atrybuty aby bylo wiadomo czy uzywamy jawnego czy niejawnego indeksu
# loc - pozwala indeksowac i wycinać fragmenty obiektu na podstawie JAWNEGO indeksu

data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: str

In [ ]:
# uzyty niejawny indeks
data[1:3]

3    b
5    c
dtype: str

In [40]:
data.loc[1]

'a'

In [ ]:
# uzyty jawny indeks
data.loc[1:3]

1    a
3    b
dtype: str